### ISSUE TITLE
Implement Automated Testing

### ISSUE THREAD

**Issue by NathanThus** [T3-FindIt/FindIt#3]

**Comment by TomVer99** [comment]
Style checking klaar voor nu.

**Comment by NathanThus** [comment]
Basic embedded setup added. Working on documentation

**Comment by NathanThus** [comment]
- [ ] Test folder CMAKE lists
- [ ] CMAKE list README
- [ ] Main CMAKE check

**Comment by NathanThus** [comment]
@TomVer99 Wat moet er nog gebeuren?
