### ISSUE TITLE
Talking skeleton - Master

### ISSUE THREAD

**Issue by NathanThus** [T3-FindIt/FindIt#34]
**DEADLINE: Sprint 4**

Wi-Fi
I2C

**Comment by TomVer99** [comment]
EN
Small comment:
This is the issue for the ESP-32 talking skeleton. The ESP-32 is the master in our system. Do not confuse this with the "Talking-Skeleton-Master" Branch

NL
Kleine opmerking:
Dit is de kwestie voor het ESP-32 talking skeleton. De ESP-32 is de master in ons systeem. Verwar dit niet met de "Talking-Skeleton-Master" Branch

**Comment by NathanThus** [comment]
Wellicht een pull-request naar de Talking-Skeleton-Master branch?

**Comment by NathanThus** [comment]
Switch case zit een fout in, zorg voor een aparte functie wat betreft data in de registers stoppen.

**Comment by NathanThus** [comment]
To whoever is going to continue working on this after the basic skeleton is finished, There'll need to be an array of addresses.
